### ISSUE TITLE
Minify fails on already minified javascript

### ISSUE THREAD

**Issue by mperham** [thumblemonks/smurf#6]
```
<%= javascript_include_tag :defaults, :cache => true, :concat => true %>

ActiveSupport.on_load(:action_view) do
  ActiveSupport.on_load(:after_initialize) do
    ActionView::Helpers::AssetTagHelper::register_javascript_expansion :defaults => ['modernizr-1.5.min', 'rails', 'application']
  end
end

Unterminated RegExp Literal
vendor/plugins/smurf/lib/smurf/javascript.rb:164:in `action'
vendor/plugins/smurf/lib/smurf/javascript.rb:221:in `jsmin'
vendor/plugins/smurf/lib/smurf/javascript.rb:51:in `initialize'
```

The problem is modernizr-1.5.min which has already be minified and apparently your pure-Ruby javascript minifier does not handle part of its syntax.  You can find modernizr here:

http://www.modernizr.com/

**Comment by mperham** [comment]
Was able to work around the problem at runtime:

```
# lib/smurf/javascript.rb line 47
def initialize(content)
  @input = StringIO.new(content)
  begin
    @output = StringIO.new
    jsmin
  rescue RuntimeError => ex
    puts "Unable to minify Javascript: #{ex.message}"
    @output = StringIO.new(content)
  end
end
```

**Comment by gus** [comment]
This stinks for Smurf. Would you be willing to fix Smurf and submit a patch?
